### ISSUE TITLE
Organize imports removes some needed imports

### ISSUE THREAD

**Issue by carlosrovira** [BowlerHatLLC/vscode-nextgenas#187] opened 2018-03-12 16:16 UTC
Hi,

I use organize imports with org.apache.royale.html.beads.layouts.HorizontalLayout.as in Royale, and it remove lots of imports, for example, IBeadModel, ILayoutHost, ILayoutParent, Event,... all that's ok, but at the same time it removes still needed imports like: ILayoutChild, ILayoutView or ValuesManager.

**Comment by joshtynjala** [comment] 2018-03-12 18:54
Thanks, Carlos. I'll take a look!

**Comment by joshtynjala** [comment] 2018-03-15 21:36
This is currently a known issue when using compiler constants. In the following code, when CONFIG::SWF is false, the compiler completely skips the entire block:

``` actionscript
COMPILE::SWF
{
	var contentView:ILayoutView = layoutView;
	//...omitted for brevity...
}
```

That basically makes the code intelligence inside Visual Studio Code completely blind to the contents of that block. In other words, it thinks that ILayoutView is not actually used. so it's safe to remove the import.

On the other hand, if you were to set targets to ["SWF, "JSRoyale"] instead of "["JSRoyale", "SWF"], CONFIG::SWF would be true instead. That block would no longer be skipped, and it would become visible to the code intelligence. VSCode would know not to remove ILayoutView from the imports because it can see the usage. Of course, that would mean that CONFIG::JS is false instead, so any types used in CONFIG::JS blocks might be removed instead.

I'll try to see if I can force the compiler to set both CONFIG::JS and CONFIG::SWF to true, so that this and other code intelligence features can be enabled, regardless of which targets you have specified.

In the meantime, I'm going to close this as a duplicate of #155 because it's definitely the same issue.

**Closed by joshtynjala** 2018-03-15 21:36 UTC
Labels: bug

**Comment by carlosrovira** [comment] 2018-03-16 14:29
Ok Josh, thanks I'll comment in the other thread.
I think is important to get to some solution here since in Royale COMPILE::XX should even increase if we add more outputs. So having code intelligence only see the first one is a problem since normally we'll have at least two (JS and SWF) hence, we could never use this feature. Hope you find a solution to make all COMIPLE:: be processed. Thanks! :)
