### ISSUE TITLE
Cannot debug and code Intellisense not working

### ISSUE THREAD

**Issue by gurtejsingh** [BowlerHatLLC/vscode-nextgenas#105] opened 2017-07-12 09:11 UTC
I cannot get to configure intellisense to work on any Flex/AIR project. Tried an existing project, a new project etc. I am not using FlexJS but I want to compile a regular Flex/AIR project. 

Here are my steps of installation: 
1. Installed the extension from within VSCode. 
2. All the settings pointed to null, manually populated them with the following values: 

  "nextgenas.sdk.editor": "/usr/local/lib/node_modules/flexjs",
  "nextgenas.java": "/usr/libexec/java_home",
  "nextgenas.sdk.framework": "/Users/xxx/Downloads/4.6.0" 

(Using the original Flex SDK bundled with Flash Builder. I have tried 4.16 from the Apache Flex SDK installer and also downloaded and merged AIR SDK, no change. Masked username with xxx above, but the path is correct in my settings)

Note, I installed FlexJS using NPM, but it did not populated any PATH variables or set the FLEX_HOME directory, I don't know why.

I cannot get any intellisense to work, yes tried a new project also:

<img width="753" alt="screen shot 2017-07-12 at 2 32 45 pm" src="https://user-images.githubusercontent.com/2323141/28110138-0cb7da16-670f-11e7-9ab5-59072dfaced6.png">

It looks nothing like what examples I have seen on the site. 

Followed the wiki steps and got the asconfig.json configured correctly and created the launch.json configuration.

When I try to build a Flex-AIR project using the 4.16 SDK, it just fails saying : 
**Error: /<PathtoMXML>.mxml is of an unsupported type: mxml**

When I try to Build with Flex 4.6.0 SDK, it succeeds. 

However, I cannot get the project to debug and launch. I get the following error in VSCode: 
**ERROR: Debug adapter process has terminated unexpectedly.**

<img width="1035" alt="screen shot 2017-07-12 at 2 35 15 pm" src="https://user-images.githubusercontent.com/2323141/28110252-63339c86-670f-11e7-8c79-194d74b72d58.png">

I've been pulling my hair out to get this to work. Any guidance would be great. Thanks for creating this awesome extension. 

Please help. Thank you. 

System Config : Mac OS Sierra 10.12.4 (16E195)
VSCode : Version 1.14.0 (1.14.0)

**Comment by joshtynjala** [comment] 2017-07-12 14:06
I'm sorry you're having some trouble with the extension. Hopefully, I can help!

> "nextgenas.java": "/usr/libexec/java_home",

This won't work, and it's probably why you're having trouble. nextgenas.java needs to point to the `java` executable (I'll double-check the documentation to be sure that this is clear). On my system, that would be the following path:

"nextgenas.java": "/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java"

However, it's worth mentioning that you can often leave nextgenas.java as null. As long as Java's bin directory is on your PATH environment variable, you shouldn't need to set nextgenas.java.

> Note, I installed FlexJS using NPM, but it did not populated any PATH variables or set the FLEX_HOME directory, I don't know why.

As I understand it, when you first install Node.js, the PATH environment variable will be populated with a special directory for npm modules. When you install anything from npm globally, it gets added to this existing directory, and PATH won't be modified every time.

FLEX_HOME will not be populated when you install FlexJS. You don't need to do that, but if you want to, it's your responsibility.

**Comment by joshtynjala** [comment] 2017-07-12 14:08
Debugging will probably also start working after you fix nextgenas.java. The debugger also runs on Java.

**Comment by joshtynjala** [comment] 2017-07-12 14:12
I should add that this also works for me (so you shouldn't be required to find where Java is installed):

"nextgenas.java": "/usr/bin/java"

**Comment by gurtejsingh** [comment] 2017-07-12 15:24
Thanks a ton for the reply @joshtynjala. 

Tried the following things but some how it's still not working. I apparently had JDK1.6. Downloaded 1.8 and now my JAVA_HOME path is (from printenv): 

JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home

But I do have another 1.6 path lying at that JavaVirtualMachines folder, I don't think that should be an issue though.

I actually removed the setting for 'nextgenas.java' and it booted up fine. But now I have the following error:

java.lang.reflect.InvocationTargetException

No code intellesense as of yet. Can you help with this error?

Again, thanks a bunch for replying back. Cheers.

**Comment by joshtynjala** [comment] 2017-07-12 15:26
Is there any other text that provides details about the error?

**Comment by gurtejsingh** [comment] 2017-07-12 15:28
Nope. The moment I shift to an MXML file from an existing Flash Builder project, it seems to popup. Just tried it with a new AS project, intellesense seems to work! I'll try debugging. Thanks!

**Comment by gurtejsingh** [comment] 2017-07-12 15:34
Also any idea about this error here : When I try to build a Flex-AIR project using the 4.16 SDK, it just fails saying :
Error: /.mxml is of an unsupported type: mxml

Also, I am getting an exit code 7 when trying to debug. I think it's to do with the namespace. I think its 3.4 for Flex 4.6.0, is there a way to find out? Thanks a lot!

**Comment by joshtynjala** [comment] 2017-07-12 15:37
> I have tried 4.16 from the Apache Flex SDK installer and also downloaded and merged AIR SDK

Did you get "Error: /.mxml is of an unsupported type: mxml" when you tried the Apache Flex SDK that you got with the installer, or was it only with the merged version?

I ask because it's possible that you merged the wrong AIR SDK. There's one version of the AIR SDK with a compiler and one without. If you want to merge the Flex SDK with the AIR SDK, you need the version of the AIR SDK without a compiler. Otherwise, there could be conflicts between the two different compilers.

**Comment by joshtynjala** [comment] 2017-07-12 15:40
> Also, I am getting an exit code 7 when trying to debug. I think it's to do with the namespace. I think its 3.4 for Flex 4.6.0, is there a way to find out? Thanks a lot!

There should be an AIR SDK Readme.txt file in your SDK. It will tell you which version of the AIR SDK is included.

**Comment by joshtynjala** [comment] 2017-07-12 15:41
Also, if you run the following command, it should tell you the version:

``` bash
/Users/xxx/Downloads/4.6.0/bin/adt -version
```

**Comment by joshtynjala** [comment] 2017-07-13 17:40
Were you able to get it working?

**Comment by gurtejsingh** [comment] 2017-07-13 18:12
Hi @joshtynjala. Apologies for the late response. I did try downloading the Flex SDK again and the AIR SDK as well and merge again (this time the non-compiler one). It gave me the following error : **Compiler not found in SDK. Expected: null**. So looks like I still need the one with the compiler. With the Flex 4.6.0 SDK, I was able to launch, but ADT immediately disconnects without any error and closes. This is on a new project (AS only). Code intellesense seems to work like a charm in new projects (AS files tested only)

For an existing Flex project (created in Flash Builder, Flex + AIR desktop), I still get the error I mentioned above : **java.lang.reflect.InvocationTargetException.** Code intellesense does not seem to work either. 

While I understand I might me doing this wrong, and I am sure the extension works fine (it looks awesome!). This could very well be a setup issue at my end. For now, I am resuming back dev within Flash Builder, while I promise to get back to this sometime soon. 

Please feel free to close the ticket. Again, apologies for the tardy response, and thank you so much for the help! Please let me know if you would like to investigate further, I would be glad to help out with screenshots and installation steps, machine configs, whatever could help to make this extension even greater!

**Comment by joshtynjala** [comment] 2017-07-13 19:59
> I did try downloading the Flex SDK again and the AIR SDK as well and merge again (this time the non-compiler one). It gave me the following error : Compiler not found in SDK. Expected: null. So looks like I still need the one with the compiler.

I saw that you're on macOS. Did you use copy/paste in the Finder? Unfortunately, when there are directories that have the same name, it will delete the old directory and replace it with the new directory instead of merging the two. That may be what happened here.

The following instructions from Adobe explain how to merge a new version of the AIR SDK with Flex 4.6, but these same instructions will also work to merge with the Apache Flex SDK too:

https://helpx.adobe.com/x-productkb/multi/how-overlay-air-sdk-flex-sdk.html

It's also worth mentioning that the Apache Flex SDK has some more dependencies besides the AIR SDK. If it were just the AIR SDK that needed to be merged, there probably wouldn't have been an official installer app. There's a special Ant script called installer.xml in the Apache Flex SDK that needs to be run to download all of the dependencies and make a few tweaks to the SDK. The Flex SDK Installer uses this, but you can also run it manually with Ant on the command line.

> With the Flex 4.6.0 SDK, I was able to launch, but ADT immediately disconnects without any error and closes.

Hopefully this will be easier in version 0.5 of the extension. The debugger will be bundled with the extension, so it won't need to try to find the one from the Flex SDK.

> For an existing Flex project (created in Flash Builder, Flex + AIR desktop), I still get the error I mentioned above : java.lang.reflect.InvocationTargetException. Code intellesense does not seem to work either.

This sounds like a bug in the extension. I hope you'll give it a try again when I release version 0.5 in the coming week. Some bugs have been fixed, and maybe one of them is what you're encountering here!

**Closed by joshtynjala** 2017-07-13 19:59 UTC

**Comment by gurtejsingh** [comment] 2017-07-21 09:42
Hi @joshtynjala I tried out the 0.5 version which you have just released, but alas, the problem with code intellesense still remains with existing projects created in Flash Builder (Flex + Desktop AIR). The error has now changed to the below error: 

<img width="1038" alt="screen shot 2017-07-21 at 3 09 33 pm" src="https://user-images.githubusercontent.com/2323141/28458274-d41edb36-6e26-11e7-8326-d43be6bc117b.png">

Just bringing this to your notice. I will be trying compiling and debugging later. Thanks.

**Comment by joshtynjala** [comment] 2017-07-21 15:31
Can you try to send me a project that doesn't work for you? Just zip up the full directory and I'll take a look at it in VSCode on my machine. That seems like the best way to debug this issue.

Ideally, if you could simplify the project as much as possible, but still make it able reproduce the issue, that will help me a lot. Thanks!

**Comment by gurtejsingh** [comment] 2017-07-24 09:37
Hey @joshtynjala Sorry for the tardy response. I created a simple new Flex AIR project in Flash Builder and tried to open it up with VSCode. I got the same error as I noted above when it booted up. I anyways went ahead and created the asconfig and build tasks but I still could not get code completion to work. The project launched fine.

However, I noticed that the type of file in the status bar below was set to NextGen Actionscript by default for MXML files (should it not detect it to be MXML by default?), I changed it to MXML and voila, I think I got intellesense to work partially.It stops working if I change it back. It does provide me with autocomplete options (note that it's not showing me completion options like `Generate Event Handler`' for predefined methods like preinitialize or creation complete like FB does). I don't know if that is something which works out of the box. 

One thing that I saw different this time is that when I hover over the method name (`onInitialized(event)`) used for creation complete for example which is this code: `creationComplete='onInitialized(event)'` I get the following errors in the output tab: 

**[Error - 2:56:02 PM] Request textDocument/hover failed.
  Message: Internal error, please look at the server's logs.
  Code: -32603** 

Similarly, when I do a CMD+click, I get the following error:

**[Error - 2:58:35 PM] Request textDocument/definition failed.
  Message: Internal error, please look at the server's logs.
  Code: -32603** 

<img width="1440" alt="screen shot 2017-07-24 at 2 59 40 pm" src="https://user-images.githubusercontent.com/2323141/28517031-be72ee24-7080-11e7-94e6-6c56dab7a231.png">

Attached screenshot above for the same. It seems to work fine for the actual declaration inside the script tag however. 

I am attaching the sample project for your review. Here's the setup I used for this project:

Project path : /Documents/Adobe Flash Builder 4.7/AIRTest
Settings : `"nextgenas.sdk.editor": "/usr/local/lib/node_modules/flexjs",
  "files.associations": {
    "*.mxml": "nextgenas"
  },
  "nextgenas.sdk.framework": "/Users/gdogra/Downloads/FlexSDK_4.15_AIR_23"`

I downloaded the FlexSDK via the Installer. I don't remember making any changes to it. 

Cheers and I hope this helps. Thanks a lot for the support.

[AIRTest.zip](https://github.com/BowlerHatLLC/vscode-nextgenas/files/1169375/AIRTest.zip)

**Comment by joshtynjala** [comment] 2017-07-24 15:38
> One thing that I saw different this time is that when I hover over the method name (onInitialized(event)) used for creation complete for example which is this code: creationComplete='onInitialized(event)' I get the following errors in the output tab

Thanks! I've actually fixed these issues already. It was a bug in the extension. I will be releasing a v0.5.1 update soon!

> (note that it's not showing me completion options like Generate Event Handler' for predefined methods like preinitialize or creation complete like FB does). I don't know if that is something which works out of the box.

The extension does not currently have a feature to generate event listeners. I have a feature request open already, though: #45

> "nextgenas.sdk.editor": "/usr/local/lib/node_modules/flexjs"

Starting with version 0.5 of the extension, the nextgenas.sdk.editor setting is no longer required. Some advanced users that are testing nightly builds of FlexJS might still want to use it, but if you've set nextgenas.sdk.framework to any other SDK (this includes how you've set it Flex 4.15), then nextgenas.sdk.editor should not be necessary anymore.

> "files.associations": { "*.mxml": "nextgenas" }

You should not need to set the *.mxml file association in your workspace or user settings. However, if the default association doesn't seem to work, you should actually set it like this instead:

```
"files.associations": {
	"*.mxml": "mxml"
}
```
