### ISSUE TITLE
Error in MXML files

### ISSUE THREAD

**Issue by carlosrovira** [BowlerHatLLC/vscode-nextgenas#257] opened 2018-08-23 19:49 UTC
Hi, 

I'm getting this error in some files since latest update:

java.lang.NullPointerException
    at org.apache.royale.compiler.internal.tree.as.BinaryOperatorPlusNode.isNumericType(BinaryOperatorPlusNode.java:127)
    at org.apache.royale.compiler.internal.tree.as.BinaryOperatorPlusNode.resolveType(BinaryOperatorPlusNode.java:75)
    at org.apache.royale.compiler.internal.semantics.MethodBodySemanticChecker.checkImplicitConversion(MethodBodySemanticChecker.java:374) 
...

The error is longer but is hard to copy.
Some lines in the MXML file gets red pointing to an error, and a popup with scroll shows in vscode showing this.

**Comment by joshtynjala** [comment] 2018-08-23 20:11
Do you have multiple root folders in your workspace?

**Comment by joshtynjala** [comment] 2018-08-23 20:13
Just in case you aren't sure what I mean:

https://code.visualstudio.com/docs/editor/multi-root-workspaces

**Comment by joshtynjala** [comment] 2018-08-23 20:34
Can you try to copy the complete call stack from the error? It will be difficult to debug if I don't know where it originates inside the VSCode extension.

**Comment by joshtynjala** [comment] 2018-08-23 20:38
Also, just to confirm, you're seeing this error being printing to VSCode's Output view, right?

**Comment by carlosrovira** [comment] 2018-08-24 09:54
Hi Josh,
yes, I see the error printed in output view. This is the full stack trace error. Hope this helps. Thanks:

java.lang.NullPointerException
	at org.apache.royale.compiler.internal.tree.as.BinaryOperatorPlusNode.isNumericType(BinaryOperatorPlusNode.java:127)
	at org.apache.royale.compiler.internal.tree.as.BinaryOperatorPlusNode.resolveType(BinaryOperatorPlusNode.java:75)
	at org.apache.royale.compiler.internal.semantics.MethodBodySemanticChecker.checkImplicitConversion(MethodBodySemanticChecker.java:374)
	at org.apache.royale.compiler.internal.semantics.MethodBodySemanticChecker.checkAssignment(MethodBodySemanticChecker.java:246)
	at org.apache.royale.compiler.internal.as.codegen.ABCGeneratingReducer.reduce_assignToMemberExpr_to_void_expression(ABCGeneratingReducer.java:2906)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.action_235(CmcEmitter.java:4431)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.dispatchAction(CmcEmitter.java:8056)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceAntecedent(CmcEmitter.java:39126)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.dispatchAction(CmcEmitter.java:9361)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceAntecedent(CmcEmitter.java:39126)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduce(CmcEmitter.java:39103)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceSubgoals(CmcEmitter.java:39154)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceAntecedent(CmcEmitter.java:39125)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduce(CmcEmitter.java:39103)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceSubgoals(CmcEmitter.java:39145)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceAntecedent(CmcEmitter.java:39125)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduce(CmcEmitter.java:39103)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.burm(CmcEmitter.java:39405)
	at org.apache.royale.compiler.internal.as.codegen.ABCGenerator.generateInstructions(ABCGenerator.java:233)
	at org.apache.royale.compiler.internal.as.codegen.ABCGenerator.generateMethodBodyForFunction(ABCGenerator.java:398)
	at org.apache.royale.compiler.internal.as.codegen.ABCGenerator.generateMethodBodyForFunction(ABCGenerator.java:352)
	at org.apache.royale.compiler.internal.as.codegen.ABCGenerator.generateFunction(ABCGenerator.java:267)
	at org.apache.royale.compiler.internal.as.codegen.ClassDirectiveProcessor.declareFunction(ClassDirectiveProcessor.java:886)
	at org.apache.royale.compiler.internal.as.codegen.DirectiveProcessor.processNode(DirectiveProcessor.java:219)
	at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.processNode(MXMLClassDirectiveProcessor.java:1117)
	at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.traverse(MXMLClassDirectiveProcessor.java:862)
	at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.traverse(MXMLClassDirectiveProcessor.java:832)
	at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.processMXMLScript(MXMLClassDirectiveProcessor.java:4154)
	at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.processNode(MXMLClassDirectiveProcessor.java:983)
	at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.traverse(MXMLClassDirectiveProcessor.java:862)
	at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.traverse(MXMLClassDirectiveProcessor.java:832)
	at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.processMainClassDefinitionNode(MXMLClassDirectiveProcessor.java:654)
	at org.apache.royale.compiler.internal.as.codegen.GlobalDirectiveProcessor.declareMXMLDocument(GlobalDirectiveProcessor.java:518)
	at org.apache.royale.compiler.internal.as.codegen.DirectiveProcessor.processNode(DirectiveProcessor.java:237)
	at org.apache.royale.compiler.internal.as.codegen.DirectiveProcessor.traverse(DirectiveProcessor.java:193)
	at org.apache.royale.compiler.internal.as.codegen.ABCGenerator.generate(ABCGenerator.java:124)
	at org.apache.royale.compiler.internal.units.MXMLCompilationUnit.handleABCBytesRequest(MXMLCompilationUnit.java:199)
	at org.apache.royale.compiler.internal.units.CompilationUnitBase.processABCBytesRequest(CompilationUnitBase.java:875)
	at org.apache.royale.compiler.internal.units.CompilationUnitBase.access$300(CompilationUnitBase.java:108)
	at org.apache.royale.compiler.internal.units.CompilationUnitBase$4$1.call(CompilationUnitBase.java:312)
	at org.apache.royale.compiler.internal.units.CompilationUnitBase$4$1.call(CompilationUnitBase.java:308)
	at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:228)
	at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by carlosrovira** [comment] 2018-08-25 07:27
Hi Josh,
I removed the complete folder in Application Support/Code
Open again VSCode and open JewelExample
Open DateComponentsPlayGround.mxml
Hit Enter inside Script block and get the error

Maybe there's some other cache for plugins? or this extension should run with other Java version?

thanks

**Comment by carlosrovira** [comment] 2018-08-25 07:36
I commented all offending code to get rid of all 4 red errors and started typing the same code to see where the problem is:

private function dateChooserDefaultChanged():void
			{
				dateChooserDefaultSelectedDate.html = "h" 

inserting a "+" after the "h" string generates the red error.
html var is a String of the Label component, so I think is ok from code perspective.
Maybe "html" could be a problematic "keyword" and something in VSCode is interfering?

thanks

**Comment by carlosrovira** [comment] 2018-08-25 08:11
Hi Josh,
as I investigate I think this could be a problem with the SDK I generate. I create a distribution build with maven with the current develop state.

Opening MXML with Script block and making some modification use to report some error in that file. 
For example I'm finding basic types problems like this in GridPlayGround.mxml:

{
	"resource": "/Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/JewelExample/src/main/royale/GridPlayGround.mxml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "1046",
	"severity": 8,
	"message": "Type was not found or was not a compile-time constant: Boolean.",
	"startLineNumber": 28,
	"startColumn": 31,
	"endLineNumber": 28,
	"endColumn": 38
}

This is for this code:

<fx:Script>
        <![CDATA[
            [Bindable]
            public var useGap:Boolean = true;
    	]]>
	</fx:Script>

I saw something similar for "String" in other file

If I remove from asconfig.json the SWF target I Get this error:

unable to open '/Users/carlosrovira/Dev/Royale/Sdks/apache-royale-snapshot/js/libs/royale.typedefs-js-0.9.3-SNAPSHOT-typedefs.swc'.
/Users/carlosrovira/Dev/Royale/Sdks/apache-royale-snapshot/frameworks/flex-config.xml (line: 80)

(I don't know how this file affects me since I'm building with maven with tasks.json CMD+SHIFT+B)

**Comment by carlosrovira** [comment] 2018-08-25 08:30
Josh,
is something related to the generated SDK. Maybe could you create a build distribution with this command:

mvn -s settings-template.xml -DdistributionTargetFolder=/Users/carlosrovira/Dev/Royale/Sdks/apache-royale-0.9.3-SNAPSHOT -P build-distribution clean install

and figure what could be the problem? Maybe with a little change we can make it play nicely with the extension.

Please let me know what do you think

thanks in advance

**Comment by joshtynjala** [comment] 2018-08-25 15:53
Whenever I've built a Maven distribution, I've had to modify that path from "royale.typedefs-js-0.9.3-SNAPSHOT-typedefs.swc" to "royale-typedefs-js-0.9.3-SNAPSHOT-typedefs.swc" in flex-config.xml. It seems to be a typo. Something needs to be fixed in the Maven distribution build.

The missing classes like Boolean are because you need playerglobal.swc when you enable the SWF target.

**Comment by carlosrovira** [comment] 2018-08-26 08:02
Thanks Josh, I think I fixed the typos in typedefs, and this seems to fix this bug! :)

about missing playerglobal.swc, where should I have it? (just to make sure of where I should search for it)

Thanks! :)

**Comment by joshtynjala** [comment] 2018-08-28 20:04
*playerglobal.swc* should be added to the SDK at *frameworks/libs/player/XX.X/playerglobal.swc*. Replace XX.X with the version of the `target-player` compiler option specified in *flex-config.xml*.

Adobe offers [old versions of *playerglobal.swc*](https://helpx.adobe.com/flash-player/kb/archived-flash-player-versions.html) for download, if needed.

Back in the Flex SDK days, the installer would download the appropriate file and place it in the correct location automatically. It looks like *royale-asjs* includes an Ant script named *InstallAdobeSDKs.xml* that can users can run to conveniently add the missing pieces for AIR/Flash support to a Royale SDK.

**Closed by joshtynjala** 2018-08-28 20:04 UTC

**Comment by carlosrovira** [comment] 2018-08-31 13:45
Many thanks Josh! I'll try to add playerglobal.swc with SWF as I get some time and try this. For now AS3 extension is now working great with maven build distribution! :) 
It would be great to finally test if the SDK generated localy is not only giving code intelligence but it can be used as a normal Royale SDK adding the AIR/Flash pieces. If so, I think that would be very cool! :)

Thanks! :)

**Comment by carlosrovira** [comment] 2018-08-31 20:56
Hi Josh,

I commit a change to maven distribution files: 
https://github.com/apache/royale-asjs/commit/f86cdea85d8abbdb8aa540d7d4e1efda86866ed2

this seems to fix the path to playerglobal.swc.
By default distribution creates a SDK with a playerglobal.swc (20.0) which seems very convenient
in flex-config.xml with the commit changes we get:

<swf-external-library-path>
          <path-element>libs/player/20.0/playerglobal.swc</path-element>
      </swf-external-library-path> 

So it seems all is in place.

In Jewel library I as well made changes to get code-intelligence in libraries. It seems it was with a bad configuration until now. This is the project 👍 

https://github.com/apache/royale-asjs/tree/develop/frameworks/projects/Jewel

And now files are found and get code intelligence but not with Flash classes as you can see in the screenshot

![captura de pantalla 2018-08-31 a las 22 54 23](https://user-images.githubusercontent.com/1701640/44935404-dec20600-ad70-11e8-8289-99c3ddb79d96.png)

Do you know what could be the problem? I think I'm about a 1% of getting AS3 Extension and VSCode working great! :)
I'm loving your extension Josh! :)

Thanks

Carlos

**Comment by carlosrovira** [comment] 2018-08-31 20:58
the following was cut, I'll try again, I want to say:

in flex-config.xml with the commit changes we get:
`<swf-external-library-path>
          <path-element>libs/player/20.0/playerglobal.swc</path-element>
      </swf-external-library-path>`
So it seems all is in place.

**Comment by joshtynjala** [comment] 2018-08-31 21:42
In *asconfig.json*, "SWF" needs to be listed before "JSRoyale" to make the compiler see the classes in *playerglobal.swc*.

**Comment by carlosrovira** [comment] 2018-08-31 21:59
Hi Josh I tried but wit no luck:

Here's the actual asconfig.json:


``` {
    "config": "royale",
    "type": "lib",
    "compilerOptions": {
        "target-player": "20.0",
        "debug": true,
        "targets": [
            "SWF", 
            "JSRoyale"
        ],
        "include-classes": [
            "src/main/royale/JewelClasses.as"
        ],
        "source-path": [
            "src/main/royale"
        ],
        "output": "target/Jewel.swc"
    }
}```

Do you see something wrong? thanks!

**Comment by joshtynjala** [comment] 2018-08-31 22:13
I see that there's also an error that it cannot find `org.apache.royale.core.CSSTextField`, which is inside a `COMPILE::JS` conditional compilation block. For some reason, it's still behaving as if "JSRoyale" were defined before "SWF" in `targets`. Can you try restarting VSCode to see if that makes a difference?

**Comment by carlosrovira** [comment] 2018-09-01 07:41
Hi Josh,
I tried to restart VSCode, but that make no difference.

I'm finding that JewelExample doesn't have error but is because there's not flash imports (what is normal in a final App. But If I try to import some flash class (i.e: import flash.display.Shape;) the result is the same as in library.

To understand better the issue. What needs VSCode and AS3 Extension to know about flash/swf classes? I understand is:

1. have playerglobal.swc inside the SDK used in  frameworks/libs/player/XX.X/playerglobal.swc
2. be referenced in flex-config.xml:
       1. In target-player
```<target-player>20.0</target-player>```
       2. In swf-external-library-path
```<swf-external-library-path>
          <path-element>libs/player/20.0/playerglobal.swc</path-element>
      </swf-external-library-path>```
I see this as well:
<!-- List of SWC files or directories that contain SWC files. -->
      <swf-library-path>
         <path-element>libs</path-element>
         <path-element>libs/player/20.0</path-element>
      </swf-library-path>

There's something more involved?

Thanks Josh

**Comment by joshtynjala** [comment] 2018-09-01 15:51
Other than that, as I said before, "SWF" should be listed before "JSRoyale" for the `targets` compiler option.

One thing that doesn't look correct is that *libs/player/20.0* should **not** be listed in *swf-library-path*. It should only be external.

**Comment by joshtynjala** [comment] 2018-09-01 16:00
I'll take a look at this next week to make sure that no bugs have been introduced recently. However, I would have expected to hear from Harbs or others if Royale's SWF target had suddenly broken. It may be some difference with the Maven distribution.

**Comment by carlosrovira** [comment] 2018-09-01 16:04
Hi Josh,
that's for sure, I think something is needed that I'm not aware of. So discovering it could be what makes the difference. Don't think SWF is broken, just something is not setup in the right way.
Thanks for looking at this. I'll be waiting to know about your findings :)

**Comment by joshtynjala** [comment] 2018-09-04 19:58
@carlosrovira I can reproduce with a non-Maven SDK too. I've determined that this was a bug in the VSCode extension, and the fix will be included in v0.14.

**Comment by joshtynjala** [comment] 2018-09-04 19:59
I think the bug was introduced when I migrated from the FlexJS compiler to the Royale compiler. It's likely that most people are targeting JS instead of SWF in Royale projects, so that's probably why it wasn't noticed until now. Thanks for bringing it up so that I could get it fixed!

**Comment by carlosrovira** [comment] 2018-09-05 08:09
Hi Josh,
that's great! I was getting crazy trying things with no luck
I'll be waiting for this fix.
Thanks! :)
