### ISSUE TITLE
Document Class Not Located In Project's Source Path error when adding new folder to workspace

### ISSUE THREAD

**Issue by angelhdz** [BowlerHatLLC/vscode-nextgenas#266] opened 2018-09-07 08:10 UTC
I built a **Python** script to create a project folder and it's dependencies (files/folders and config files).

> **Steps to reproduce:**

- Run the Python script in the terminal and create the project
- After the project folder and its dependencies are created, the Python script then calls the VS Code terminal code `Code --add {folder name}` to add the folder to the current Workspace.
- The folder is added to the Workspace successfully.
- Compile the project with CTRL + ENTER as usual.
- Error: **"Document Class not located in project's source path. Code intelligence
will not be available for this file. (1, 1)"**
- Reload Window
- Error goes away

https://youtu.be/CIBMzVwNlqc

**Comment by angelhdz** [comment] 2018-09-07 08:28
Issue can be also reproduced with @neminovno 's extension 
[https://github.com/neminovno/vscode-as-fx-ide](url)

- Create a project with @neminovno 's extension in current Workspace
- After project is created, the error is raised. Goes away with a **Reload Window**.

**Comment by joshtynjala** [comment] 2018-09-07 17:16
Confirmed. Code intelligence doesn't work when you add a new folder to an existing workspace unless you restart the language server.

I also tried modifying *asconfig.json*, which sometimes works when something seems out of sync, but that didn't seem to have any effect. Something in the initial creation of the new compiler project seems to be failing.

I'll investigate.

**Comment by joshtynjala** [comment] 2018-09-07 18:18
Thanks! I determined that while I created a listener for when the workspace folders changed, I didn't actually register it. It's now fixed and will be included in the upcoming v0.14 update.

**Closed** 2018-09-07 18:18 UTC
Labels: bug

**Comment by angelhdz** [comment] 2018-09-07 18:58
**It's a pleasure meeting a very committed person.** 

I admire the way and the speed you handle the issues/bugs, and your organized workflow. These qualities are very rare nowadays. You're also kind to the people using your software and services, you don't go just like "oh, here comes Angel again with an issue, so annoying!" or "pay me and I fix your issues" as other arrogant developers I've encountered.

I will, of course, donate when I start having an income as developer (I was working as landscaper/gardener after the aftermath of Hurricane Maria here in Puerto Rico).

For the moment I'm just moving to VS Code from FlashDevelop, learning to make extensions, and practicing my Actionscript skills with personal projects. I also program in C#, Javascript/TypeScript, Python and PHP.

Overall, this **nextgenas** extension is working good. I can compile my AIR Desktop/Mobile apps beautifully. 

Thanks, again, and have a wonderful day. Blessings!

**Comment by joshtynjala** [comment] 2018-09-07 20:32
@angelhdz Thank you for the very kind words!
